#theme: jekyll-theme-slate
remote_theme: pmarsceill/just-the-docs
title: SOROTOKI 
description: A Soft Robotics Toolkit for MATLAB
show_downloads: true


# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  libary:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    libary:
      # Give the collection a name
      name: Libary usage
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
