version: '2.1'
orbs:
  matlab: mathworks/matlab@1
  
jobs:
  test:
    parameters:
      version:
        description: "MATLAB version"
        default: "latest"
        type: string
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: git clone https://github.com/mobeets/mpm.git temp
      - run: mv temp/mpi.m . & mv temp/mpi_config.m . & mv temp/mpi_nls.mat . & mkdir mpi-packages
      - run: rm -rf temp
      - matlab/install:
          release: <<parameters.version>>
          products: |
            MATLAB
            Simulink
            Image_Processing_Toolbox
            Instrument_Control_Toolbox
            MATLAB_Coder
            Mapping_Toolbox
            Optimization_Toolbox
            Partial_Differential_Equation_Toolbox
            Statistics_and_Machine_Learning_Toolbox
      - matlab/run-command:
          command: ver
      - matlab/run-command:
          command: sorotoki -i --approve; sorotoki -b --approve; y = sorotoki('-t');
          
workflows:
  matrix-tests:
    jobs:
      - test:
          name: test-<<matrix.version>>
          matrix:
            parameters:
              version:
                - R2022a
                - R2022b
                - R2023b
                - R2024a          

