clr;
%% preview
obj = Gmodel(@(x) dSphere(x,0,0,0,1),[-1,1,-1,1,-1,1]);
obj.set('TextureStretch',.65);

mat = {...
    aniso, ...
    bluered, ...
    bump, ...
    chroma, ...
    chromium, ...
    clean, ...
    copper, ...
    egg, ...
    grey, ...
    hotmetal, ...
    jade, ...
    matcap, ...
    mateplastic, ...
    metal, ...
    metalclean, ...
    oldwax, ...
    orangeresin, ...
    planet, ...
    plastic, ...
    redshine, ...
    redwax, ...
    retro, ...
    rim, ...
    soft, ...
    skin, ...
    studioclay, ...
    white, ...
};
obj.Texture = mat{1};
obj.render;
background(gitpage);
pause;
gif('preview_matcap.gif','DelayTime',0.25);

[x,y] = view;

for ii = 2:length(mat)
obj.Texture = mat{ii};
view(1e-3*ii + x, y);
obj.update;
gif
end

% assignin('base','mesh',mesh);