clr;
%% preview
obj = Gmodel(@(x) dSphere(x,0,0,0,1),[-1,1,-1,1,-1,1],'Quality',150);
obj.set('TextureStretch',.65);

mat = {...
    aniso, ...
    bluered, ...
    bump, ...
    chroma, ...
    chromium, ...
    clean, ...
    copper, ...
    egg, ...
    grey, ...
    hotmetal, ...
    jade, ...
    matcap, ...
    mateplastic, ...
    metal, ...
    metalclean, ...
    oldwax, ...
    orangeresin, ...
    planet, ...
    plastic, ...
    redshine, ...
    redwax, ...
    retro, ...
    rim, ...
    soft, ...
    skin, ...
    studioclay, ...
};

obj.Texture = mat{1};
obj.render;
background(gitpage);
zoom(1.4)
pause;
gif('matcap.gif','DelayTime',0.33,'frame',gcf);

[x,y] = view;

for ii = 2:length(mat)
obj.Texture = mat{ii};
obj.update;
gif
end
